# Generated by Django 4.0.4 on 2022-04-13 05:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Auxiliar_NPS', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='partener',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='client',
            name='rating_nps',
            field=models.IntegerField(blank=True),
        ),
    ]
